// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQmUJ9dfL6-aJflNsW1fjX2hVkCaVsuI0',
    appId: '1:473952285550:web:67572a24b4f095dbecc77f',
    messagingSenderId: '473952285550',
    projectId: 'pos-backend-flutter',
    authDomain: 'pos-backend-flutter.firebaseapp.com',
    storageBucket: 'pos-backend-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSjmIzXXGniPCCLq_IW4KGAGtjyG9eUk',
    appId: '1:473952285550:android:e2cdf72338eb0a99ecc77f',
    messagingSenderId: '473952285550',
    projectId: 'pos-backend-flutter',
    storageBucket: 'pos-backend-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCASnbOL39h-DNQumDIkoAVTjfpvJKajPM',
    appId: '1:473952285550:ios:c9466a93abdffffdecc77f',
    messagingSenderId: '473952285550',
    projectId: 'pos-backend-flutter',
    storageBucket: 'pos-backend-flutter.appspot.com',
    iosClientId: '473952285550-p96efqacrk0roof4ahe4tl3c861bshmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.funnel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCASnbOL39h-DNQumDIkoAVTjfpvJKajPM',
    appId: '1:473952285550:ios:c9466a93abdffffdecc77f',
    messagingSenderId: '473952285550',
    projectId: 'pos-backend-flutter',
    storageBucket: 'pos-backend-flutter.appspot.com',
    iosClientId: '473952285550-p96efqacrk0roof4ahe4tl3c861bshmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.funnel',
  );
}
